    <title>Test HTML</title>
version: '3'
services:

    apache-test-site:
        image: apache2-php
        ports:
            - 80:80
        volumes:
            - /home/derek/PhpStromProjects/UrbanFrontierHouse/www/:/var/www/html/
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '0.05'
                    memory: 256M
                reservations:
                    cpus: '0.01'
                    memory: 64M

#Test commands                    
#networks:
#    default:
#        external:
#            name: network-webservers
