version: '3'
services:

    bestRestingInn:
        image: apache2-php
        ports:
            - 8081:80
        volumes:
            - /var/www/html/ninja/scritch/urbanfrontier/:/var/www/html/
        deploy:
            replicas: 2
            resources:
                limits:
                    cpus: '0.05'
                    memory: 256M
                reservations:
                    cpus: '0.01'
                    memory: 64M

#Test commands                    
#networks:
#    default:
#        external:
#            name: network-webservers
